version: '2.1'
services:
  zk-server:
    image: zookeeper:3.4.10

  dubbox-consumer:
    image: skywalking/dubbox-consumer-scenario:1.0-2017
    expose:
      - "18080"
    ports:
      - "18080:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
      - ZK_ADDRESS=zk-server:2181
    links:
      - zk-server
      - dubbox-provider
      - mock-collector
    volumes:
     - {AGENT_FILE_PATH}:/usr/local/tomcat/agent
    depends_on:
      mock-collector:
        condition: service_healthy

  dubbox-provider:
    image: skywalking/dubbox-provider-scenario:1.0-2017
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
      - ZK_ADDRESS=zk-server:2181
    expose:
      - "20880"
    volumes:
     - /Users/xin/workbench/ascrutae/test-project/agent:/usr/local/dubbox-provider/agent
    links:
      - zk-server
      - mock-collector
    depends_on:
      mock-collector:
        condition: service_healthy

  mock-collector:
    image: skywalking/skywalking-mock-collector:1.0-2017
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "12800:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 5s
      timeout: 10s
      retries: 5
