version: '2.1'
services:
  async-testcase:
    image: skywalking/httpclient-scenario:3.2.3-2017
    expose:
      - "18080"
    ports:
      - "18080:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
    links:
      - mock-collector
    volumes:
      - {AGENT_FILE_PATH}:/usr/local/tomcat/agent
    depends_on:
      mock-collector:
        condition: service_healthy

  mock-collector:
    image: skywalking/skywalking-mock-collector:3.2.6-2017
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "12800:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 5s
      timeout: 10s
      retries: 5
